{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "orchestrdb-operator.fullname" . }}-role
  labels:
    {{- include "orchestrdb-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["orchestrdb.mertsaygi.net"]
    resources: ["databases", "databases/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["orchestrdb.mertsaygi.net"]
    resources: ["users", "users/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
{{- end }}
