{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orchestrdb-operator.serviceAccountName" . }}
  labels:
    {{- include "orchestrdb-operator.labels" . | nindent 4 }}
{{- end }}
