apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.orchestrdb.mertsaygi.net
spec:
  group: orchestrdb.mertsaygi.net
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
      - odb
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["host", "port", "name"]
              properties:
                host:
                  type: string
                port:
                  type: integer
                adminUser:
                  type: string
                adminPassword:
                  type: string
                name:
                  type: string
                adminSecretRef:
                  type: object
                  properties:
                    name:
                      type: string
                    userKey:
                      type: string
                    passwordKey:
                      type: string
                sslMode:
                  type: string
            status:
              type: object
              properties:
                created:
                  type: boolean
                lastError:
                  type: string
                updatedAt:
                  type: string
      subresources:
        status: {}